export const CATEGORIES = [
  "London",
  "Travel",
  "Health & Fitness",
  "Food & Drink",
  "Books",
  "Film & TV",
  "Customisable",
  "Sports",
  "Arts & Culture",
  "Daily Life",
  "Music",
  "30 day challenges",
  "Theatre",
  "Get Creative",
  "Productivity",
  "At Home",
  "Wellbeing",
  "For Kids",
]
